---
- name: Delete patch details file
  delegate_to: localhost
  become: no
  file:
    path: /tmp/patching_details.txt
    state: absent
  when:  ( yum_update is defined) and (yum_update | length > 0) and ( yum_update or yum_update.failed )

- name: Delete Katello Consumer File
  become: yes
  file:
    path: "{{ home_path }}katello-ca-consumer-latest.noarch.rpm"
    state: absent
  when: script_download is defined




