---
- name: Read list of IP's from CSV file and return a list
  become: yes
  read_csv:
    path: "{{file_path}}{{ file_name }}"
    delimiter: ','
  register: users

- name: Filtered IP's from list of hosts
  set_fact: hosts="{{ users.list | json_query(hosts_list) }}"
  vars:
    hosts_list: "[*].ip"

- name: print list of host from the CSV to be added 
  debug: msg="{{ hosts }}"