---
- hosts: localhost
  #become: sudo
  #connection: local
  vars:
   ip_list: []
   valid_ip_list: []
   final_ip_list: []
   vulnerable_ips: []
  tasks:
      - name: Include roles
        block:
            - include_role:
               name: launch_scan

            - include_role:
               name: generate_report
        always:
          - name: Create log file
            include: generate_report/tasks/logs.yml
   