---

- name: Fetch all Configurations 
  uri:
    url: "https://{{ manageengine_server }}/api/1.3/patch/viewconfig"
    headers:
       Authorization: "{{ token.json.message_response.authentication.auth_data.auth_token }}"
    method: GET
    validate_certs: no
  register: configs

- name: Check if Patch Configuration with label - {{ label }} exists
  set_fact: 
     configuration_exists: 1
  when: item.collection_name == label
  with_items: 
       - "{{ configs.json.message_response.viewconfig }}"

- name: Print the configuration Status
  debug:
     msg: "There has been error while creating Patch Configuration. Check logs at /var/log/Manageengine_job_logs/ with the job id {{ tower_job_id }} for detailed info, same has been sent in a seperate email. "
  when: configuration_exists == 0

- name: Send Email with configuration status
  include_role:
    name: common/send-email
  vars:
    mail_subject: Patch Configuration Status
    mail_body: '<p>There has been error while creating Patch Configuration with label <b>{{ label }}</b>. Check logs at /var/log/Manageengine_job_logs/ with the job id <b>"{{ tower_job_id }}"</b> for detailed info, same has been sent in a seperate email.</p>'
  when: configuration_exists == 0

- name: Print the configuration Status
  debug:
     msg: "Patch Configuration with label {{ label }} has been created Successfully. Check logs at /var/log/Manageengine_job_logs/ with the job id {{ tower_job_id }} for detailed info, same has been sent on seperate email. "
  when: configuration_exists == 1

- name: Send Email with configuration status
  include_role:
    name: common/send-email
  vars:
    mail_subject: Patch Configuration Status
    mail_body: '<p>Patch Configuration with label <b>{{ label }}</b> has been created Successfully. Check logs at /var/log/Manageengine_job_logs/ with the job id <b>"{{ tower_job_id }}"</b> for detailed info, same has been sent in a seperate email.</p>'
  when: configuration_exists == 1