---
- name: Fetch servers based on patch
  uri:
    url: "https://{{ manageengine_server }}/api/1.3/patch/allpatchdetails?patchid={{ item }}"
    headers:
       Authorization: "{{ token.json.message_response.authentication.auth_data.auth_token }}"
       Content-Type: application/json
       Accept: application/json
    validate_certs: no
    method: GET
  register: patch_details

- name: Append to the severs list
  set_fact:
     servers: "{{ servers | combine({item.resource_id: item.resource_name}) }}"
     server_name: "{{ server_name + [item.resource_name] }}"
  loop: "{{ patch_details.json.message_response.allpatchdetails }}"

