---   
 - name: Include vars file
   include_vars: ../vars/vars.yml
   no_log: True

 - name: Include request vars file
   include_vars: ../vars/request_vars.yml
   no_log: True

#call read_csv_file task here
 - name: Include read csv file
   include: read_csv_file.yml
         

 - block:
    # - name: Get Scan Engines {{date}} {{time}}
    #   uri:
    #     url: https://{{ insightvm_host }}/api/3/scan_engines
    #     user: "{{ insightvm_user }}"
    #     password: "{{ insightvm_password }}"
    #     validate_certs: no
    #     method: GET
    #     force_basic_auth: yes
    #     status_code: 200
    #   register: scan_engines
    # - debug:
    #     msg: "scan site name is {{ scan_engines }}"

    # - name: Get Scan Engine ID {{date}} {{time}}
    #   set_fact:
    #     scan_eng_id: "{{ item.id }}"
    #   with_items: "{{ scan_engines.json.resources }}"
    #   when: item.name == "{{ scan_engine_name }}"
    # - debug:
    #     msg: "id is {{ scan_eng_id }}"
    
    - name: Get Scan sites {{date}} {{time}}
      uri:
        url: https://{{ insightvm_host }}/api/3/sites
        user: "{{insightvm_user }}"
        password: "{{ insightvm_password }}"
        validate_certs: no
        method: GET
        force_basic_auth: yes
        status_code: 200
      register: scan_sites
    - debug:
        msg: "scan site name is {{ scan_site_name }}"

    - name: Get Scan Site ID {{date}} {{time}}
      set_fact:
        scan_site_id: "{{ item.id }}"
      with_items: "{{ scan_sites.json.resources }}"
      when: item.name == "{{ scan_site_name }}"
    - debug:
        msg: "scan site id is {{ scan_site_id }}"
  
    - name: Get Scan site details for scan engine id
      uri:
       url: https://{{ insightvm_host }}/api/3/sites/{{ scan_site_id }}
       user: "{{insightvm_user }}"
       password: "{{ insightvm_password }}"
       validate_certs: no
       method: GET
       force_basic_auth: yes
       status_code: 200
      register: scan_site_details
    - debug:
       msg: "scan site details"

    - name: Get scan engine id for selected scan site
      set_fact:
       scan_eng_id: "{{ scan_site_details.json.scanEngine }}"
    - debug:
       msg: "Scan engine id is  {{ scan_eng_id }}"








    - name: Get Scan templates {{date}} {{time}}
      uri:
        url: https://{{ insightvm_host }}/api/3/scan_templates
        user: "{{insightvm_user }}"
        password: "{{ insightvm_password }}"
        validate_certs: no
        method: GET
        force_basic_auth: yes
        status_code: 200
      register: scan_templates
    - debug:
        msg: "scan template is {{ scan_template }}"

    - name: Get Scan Template ID {{date}} {{time}}
      set_fact:
       scan_template_id: "{{ item.id }}"
      with_items: "{{ scan_templates.json.resources }}"
      when: 'item.name == "{{ scan_template }}"'
    - debug:
        msg: "scan template id is {{ scan_template_id }}"

    - debug:
        msg: "Scan site id={{scan_site_id}}, scan eng id={{scan_eng_id}}, scan template id={{scan_template_id}}, ip_addrs passed={{ valid_ip_list }}"

   rescue:
    # - name: Create a log file for scan process
    #    include: generate_report/tasks/logs.yml
    - name: Send an email if any task fails {{date}} {{time}}
      include_role:
       name: common/send_email
      vars:
       mail_subject: Failed to launch scan on requested site
       mail_body: 'Requested scan was not triggered on this site {{ scan_site_name }} as  entity ids for selected scan template {{scan_template}} was not found .Please check log file for more details,sent on a seperate email.'
      # mail:
      #  host: smtp.gmail.com
      #  port: 587
      #  username: "{{smtp_username}}"
      #  password: "{{smtp_password}}"
      #  to: "{{ email_id }}"
      #  subject: Failed to launch scan on requested site
      #  body: 'Hi team, requested scan was not triggered on this site {{scan_site}}.'
      # delegate_to: localhost
          
    - name: Abort this role tasks execution if no scan template,scan engine or scan site id was found {{date}} {{time}}
      fail:
        msg: Aborting playbook execution, as no scan template,scan engine or scan site ids were found
      when: scan_sites.status!= 200 or scan_templates.status!=200 or scan_site_id == '' or scan_eng_id == '' or scan_template_id == '' or ip_address  == ''
  