---
    - name: include vault_files
      include_vars: "{{ vault_file_path }}"

    - name: Sending an email notification
      delegate_to: localhost
      become: no
      mail:
        host: "{{ MAIL_HOST }}"
        port: "{{ MAIL_PORT }}"
        username: "{{ MAIL_USERNAME }}"
        password: "{{ MAIL_PASSWORD }}"
        to: "User < {{ receiver_email }}>"
        subject: "{{ mail_subject }}"
        subtype: html
        attach: "{{ attachment_file | default( [] ) }}"
        body: "{{ email_template }}"
        secure: starttls
      ignore_errors: true